version: "3"
services:
  app:
    image: node:12-alpine
    command: sh -c "npm install --production && node backend/server.js"
    ports:
      - $PORT:$PORT
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules/
    env_file: .env

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-auth-data:/var/lib/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword123

volumes:
  mongo-auth-data:
