version: "3"
services:
  app:
    image: node:12-alpine
    command: sh -c "npm install --production && node backend/server.js"
    ports:
      - $PORT:$PORT
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules/
    env_file: .env

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-auth-data:/var/lib/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - $MONGO_EXPRESS_PORT:$MONGO_EXPRESS_PORT
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD

volumes:
  mongo-auth-data:
